A_SearchJob/A_SearchJob/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('employer/', include('employer.urls'), name='home-employer'),
    path('employee/', include('employee.urls'), name='home-employee'),
    path('story/', include('story.urls'), name='home-story'),

    path('', include('employee.urls'), name='home'),

    path('users/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A_SearchJob/employee/urls.py
from django.urls import path
from employee.views import home, create_resume, update_resume, delete_resume, \
    liked_vacancies, own_resumes, vacancy, resume, like_vacancy, respond_to_vacancy

app_name = 'employee'

urlpatterns = [
    path('', home, name='home-employee'),
    path('create/', create_resume, name='create'),
    path('update/<int:id>/', update_resume, name='update'),
    path('delete/<int:id>/', delete_resume, name='delete'),

    path('liked/', liked_vacancies, name='liked'),
    path('resumes/', own_resumes, name='resumes'),

    path('vacancy/<int:id>/', vacancy, name='vacancy'),
    path('resume/<int:id>/', resume, name='resume'),
    path('like_vacancy/<int:id>/', like_vacancy, name='like_vacancy'),

    path('respond/<int:id>/', respond_to_vacancy, name='respond')
]

A_SearchJob/employer/urls.py
from django.urls import path
from employer.views import home, create_vacancy, update_vacancy, delete_vacancy, \
    liked_resumes, own_vacancies, resume, vacancy, like_resume, respond_to_resume

app_name = 'employer'

urlpatterns = [
    path('', home, name='home-employer'),
    path('create/', create_vacancy, name='create'),
    path('update/<int:id>/', update_vacancy, name='update'),
    path('delete/<int:id>/', delete_vacancy, name='delete'),

    path('vacancy/<int:id>/', vacancy, name='vacancy'),
    path('resume/<int:id>/', resume, name='resume'),
    path('like_resume/<int:id>/', like_resume, name='like_resume'),

    path('liked/', liked_resumes, name='liked'),
    path('vacancies/', own_vacancies, name='vacancies'),

    path('respond/<int:id>/', respond_to_resume, name='respond')
]

A_SearchJob/story/urls.py
from django.urls import path
from .views import home, create_story, update_story, delete_story, \
    own_stories, delete_comment, like_story, liked_stories, story_content

app_name = 'story'

urlpatterns = [
    path('', home, name='home-story'),
    path('<int:id>/', story_content, name='story-content'),

    path('create/', create_story, name='story-create'),
    path('update/<int:id>/', update_story, name='story-update'),
    path('delete/<int:id>/', delete_story, name='story-delete'),

    path('liked_stories/', liked_stories, name='stories-liked'),
    path('own_stories/', own_stories, name='story-own'),

    path('delete_comment/<int:id>/', delete_comment, name='story-delete-comment'),
    path('like_story/<int:id>/', like_story, name='story-like')
]

A_SearchJob/users/urls.py
from django.urls import path, include
from users.views import register

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register')
]

A_SearchJob/story/models.py
from django.db import models
from django.conf import settings


def types_of_profession():
    types = [
        ('employers', 'Employers'),
        ('employees', 'Employees'),
        ('everyone', 'Everyone')
    ]

    return types


# Create your models here.
class StoryModel(models.Model):
    headline = models.CharField(verbose_name='Headline of story', max_length=200)
    title = models.TextField(verbose_name='Title of story')
    text = models.TextField(verbose_name='Text of story')
    for_who = models.CharField(verbose_name='Useful for whom', max_length=20, choices=types_of_profession(), default=types_of_profession()[2][0])

    comments = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        default=1,
        on_delete=models.PROTECT
    )

    def __str__(self):
        return self.headline

    def get_url_to_story(self):
        return f'/story/{self.id}/'

    def get_url_to_update_story(self):
        return f'/story/update/{self.id}/'

    class Meta:
        ordering = ['-timestamp']
        verbose_name = 'Story'
        verbose_name_plural = 'Stories'


class CommentModel(models.Model):
    story = models.ForeignKey('StoryModel', on_delete=models.CASCADE)
    text = models.CharField(max_length=300, verbose_name='Text of comment')
    timestamp = models.DateTimeField(auto_now_add=True)

    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        default=1,
        on_delete=models.PROTECT
    )

    def __str__(self):
        return f'{self.story} - {self.id}'

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'
        ordering = ('-timestamp', )

A_SearchJob/story/forms.py
from django import forms
from story.models import StoryModel


class StoryForm(forms.ModelForm):

    class Meta:
        model = StoryModel
        fields = [
            'headline',
            'title',
            'text',

            'for_who',
            'comments'
        ]

A_SearchJob/story/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from additional_functions.additional import paginator_array, get_current_year
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from .models import StoryModel, CommentModel
from django.db.models import Q
from django.conf import settings
from users.models import User
from story.forms import StoryForm
import json


def home(request):
    queryset = StoryModel.objects.all()

    query = request.GET.get('q_story')
    if query:
        queryset = queryset.filter(
            Q(headline__icontains=query) |
            Q(for_who__icontains=query)
        )

    stories_per_page = 8
    paginator = Paginator(queryset, stories_per_page)

    page_request_var = 'page'
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.get_page(page)
    except PageNotAnInteger:
        queryset = paginator.page(paginator.num_pages)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'stories': queryset,
        'user_side': settings.USER_SIDE,
        'page_request_var': page_request_var,
        'paginator_range': paginator_array(paginator.num_pages, paginator.get_page(page).number),
        'count_of_pages': paginator.num_pages,
        'count_of_stories': len(queryset),
        'user': request.user,
        'current_year': get_current_year()
    }

    return render(request, 'story/home.html', context)


def story_content(request, id=None):

    story = get_object_or_404(StoryModel, id=id)

    user_visitor = get_object_or_404(User, id=request.user.id)
    user_author = get_object_or_404(User, username=story.user)

    if request.POST:

        comment_author = user_visitor
        comment_text = request.POST['text']

        story.commentmodel_set.create(user=comment_author, text=comment_text)

        return redirect(f'/story/{id}/')

    context = {
        'story': story,
        'id': id,
        'user_side': settings.USER_SIDE,
        'user_main': user_author,
        'comments': story.comments,
        'all_comments': story.commentmodel_set.order_by('-id'),
        'user_visitor': user_visitor,
        'current_year': get_current_year()
    }

    with open('additional_files/liked_stories.json', "r") as file:
        data = json.load(file)

    user_id = str(user_visitor.id)

    try:
        if story.id in data['users'][user_id]:
            context['existence_in_liked_stories'] = True
        else:
            context['existence_in_liked_stories'] = False
    except KeyError:
        context['existence_in_liked_stories'] = False

    return render(request, 'story/story.html', context)


def like_story(request, id):

    story = get_object_or_404(StoryModel, id=id)

    user = get_object_or_404(User, id=request.user.id)

    user_id = str(user.id)
    story_id = story.id

    with open('additional_files/liked_stories.json', "r") as file:
        data = json.load(file)

    if user_id in data['users']:
        if story_id in data['users'][user_id]:
            data['users'][user_id].remove(story_id)
        else:
            data['users'][user_id].append(story_id)
    else:
        data['users'][user_id] = [story_id]

    with open('additional_files/liked_stories.json', 'w') as file:
        json.dump(data, file)

    return redirect(f'/story/{story_id}/')


def own_stories(request):
    queryset = [story for story in StoryModel.objects.all() if story.user == request.user]

    context = {
        'own_stories': queryset,
        'count_of_stories': len(queryset),
        'user_side': settings.USER_SIDE,
        'current_year': get_current_year()
    }

    return render(request, 'story/own_stories.html', context)


def liked_stories(request):
    user = get_object_or_404(User, id=request.user.id)

    with open('additional_files/liked_stories.json', 'r') as file:
        data = json.load(file)

    user_id = str(user.id)

    try:
        liked_stories_lst = data['users'][user_id]
        queryset = StoryModel.objects.all().filter(id__in=liked_stories_lst)
    except KeyError:
        queryset = StoryModel.objects.all().filter(id__in=[0])

    query = request.GET.get('q_liked_s')
    if query:
        queryset = queryset.filter(
            Q(headline__icontains=query) |
            Q(for_who__icontains=query)
        )

    context = {
        'stories': queryset,
        'count_of_stories': len(queryset),
        'add_query': False,
        'user_side': settings.USER_SIDE,
        'current_year': get_current_year()
    }

    if query:
        context['add_query'] = True
    else:
        context['add_query'] = False

    return render(request, 'story/liked_stories.html', context)


def create_story(request):
    form = StoryForm(request.POST or None)

    if form.is_valid():
        story = form.save(commit=False)
        story.user = request.user
        story.save()

        extra_tags = 'html_safe'

        message = f'<p>The <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/story/{story.id}/">story</a> was successfully created!</p>' \
                  f'<p>To update your story, click <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/story/update/{story.id}/">here</a></p>'

        messages.info(request, message, extra_tags)

        return redirect('story:story-own')

    context = {
        'form': form,
        'headline': '',
        'title': '',
        'text': '',
        'comments': '',
        'text_for_btn': 'Create story',
        'user_side': settings.USER_SIDE,
        'current_year': get_current_year()
    }

    return render(request, 'story/story_creation.html', context)


def update_story(request, id=None):

    story = get_object_or_404(StoryModel, id=id)
    form = StoryForm(request.POST or None, instance=story)

    if form.is_valid():
        updated_story = form.save(commit=False)
        updated_story.save()

        extra_tags = 'html_safe'

        message = f'<p>The <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/story/{story.id}/">story</a> was successfully updated!</p>' \
                  f'<p>To update again your story, click <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/story/update/{story.id}/">here</a></p>'

        messages.info(request, message, extra_tags)

        return redirect('story:story-own')

    context = {
        'form': form,
        'headline': story.headline,
        'title': story.title,
        'text': story.text,
        'comments': story.comments,
        'text_for_btn': 'Update story',
        'user_side': settings.USER_SIDE,
        'current_year': get_current_year()
    }

    return render(request, 'story/story_creation.html', context)


def delete_story(request, id=None):
    story = get_object_or_404(StoryModel, id=id)
    story.delete()

    extra_tags = 'html_safe'

    message = f'<p>Story has just been successfully deleted!</p>'

    messages.info(request, message, extra_tags)

    return redirect('story:story-own')


def delete_comment(request, id=None):
    comment = get_object_or_404(CommentModel, id=id)
    story = get_object_or_404(StoryModel, headline=comment.story)

    comment.delete()

    return redirect(f'/story/{story.id}/')

A_SearchJob/templates/story/base_story_block.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SearchJob</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.4.1/dist/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body style="background-color: rgba(234,234,234,0.36); display: flex; flex-direction: column; justify-content: space-between; min-height: 100vh; margin: 0;">

    <div class="justify-content-center py-3 mb-4" style="width: 90%; margin-left: 5%; height: 70px;">

        <div class="col-md-3 mb-2 mb-md-0" style="margin-top: 7px;">
            <a href="{% if user_side == 'employee' %}{% url 'employer:home-employer' %}{% else %}{% url 'employee:home-employee' %}{% endif %}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" class="bi me-2" role="img" width="55" height="42" viewBox="0 0 46 46" fill="none">
                    <path d="M18.6875 2.875C16.3062 2.875 14.375 4.80461 14.375 7.1868V8.625H4.3125C1.93077 8.625 0 10.5558 0 12.9375V16.9169L21.8888 22.7539C22.6169 22.9481 23.3831 22.9481 24.1112 22.7539L46 16.9169V12.9375C46 10.5558 44.0692 8.625 41.6875 8.625H31.625V7.1868C31.625 4.80461 29.6938 2.875 27.3125 2.875H18.6875ZM18.6875 5.75H27.3125C28.1069 5.75 28.75 6.39581 28.75 7.18927V8.625H17.25V7.1868C17.25 6.39335 17.8931 5.75 18.6875 5.75Z" fill="black"/>
                    <path d="M0 35.9375C0 38.3192 1.93077 40.25 4.3125 40.25H41.6875C44.0692 40.25 46 38.3192 46 35.9375V19.6914L23.3704 25.726C23.1277 25.7907 22.8723 25.7907 22.6296 25.726L0 19.6914V35.9375Z" fill="black"/>
                </svg>
                <span style="color: black; font-size: 28px;" >SearchJob</span>
            </a>
        </div>

        <ul class="nav col-12 col-md-6 me-lg-auto mb-2 justify-content-center mb-md-0" style="font-size: 25px;">
            <li><a href="{% if user_side == 'employee' %}{% url 'employee:home-employee' %}{% else %}{% url 'employer:home-employer' %}{% endif %}" class="nav-link px-2">Home</a></li>
            <li><a href="{% if user_side == 'employee' %}{% url 'employee:create' %}{% else %}{% url 'employer:create' %}{% endif %}" class="nav-link px-2">Create</a></li>
            <li><a href="{% if user_side == 'employee' %}{% url 'employee:resumes' %}{% else %}{% url 'employer:vacancies' %}{% endif %}" class="nav-link px-2">{% if user_side == 'employee' %}My resumes{% else %}My vacancies{% endif %}</a></li>
            <li><a href="{% if user_side == 'employee' %}{% url 'employee:liked' %}{% else %}{% url 'employer:liked' %}{% endif %}" class="nav-link px-2">Liked</a></li>
            <li><a href="{% url 'story:home-story' %}" class="nav-link px-2 link-secondary">Stories</a></li>
        </ul>

        {% block add_in_nav %}
        {% endblock add_in_nav %}

        <hr style="margin-top: 20px;">

    </div>

    {% include 'story/messages_logic.html' %}

    {% block main_content %}
    {% endblock main_content %}

    <div class="col-sm-6 col-sm-offset-3" style="margin-left: 5%; width: 90%; margin-bottom: 30px;">
        <hr>
        <p class="col-md-4 mb-0 text-body-secondary" style="font-size: 22px; color: rgba(45,45,45,0.66); margin-top: 10px;">© {{ current_year }} Company, Inc</p>

        <a style="margin-top: 7px;" href="{% if user_side == 'employee' %}{% url 'employer:home-employer' %}{% else %}{% url 'employee:home-employee' %}{% endif %}" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" class="bi me-2" role="img" width="55" height="42" viewBox="0 0 46 46" fill="none">
            <path d="M18.6875 2.875C16.3062 2.875 14.375 4.80461 14.375 7.1868V8.625H4.3125C1.93077 8.625 0 10.5558 0 12.9375V16.9169L21.8888 22.7539C22.6169 22.9481 23.3831 22.9481 24.1112 22.7539L46 16.9169V12.9375C46 10.5558 44.0692 8.625 41.6875 8.625H31.625V7.1868C31.625 4.80461 29.6938 2.875 27.3125 2.875H18.6875ZM18.6875 5.75H27.3125C28.1069 5.75 28.75 6.39581 28.75 7.18927V8.625H17.25V7.1868C17.25 6.39335 17.8931 5.75 18.6875 5.75Z" fill="black"/>
            <path d="M0 35.9375C0 38.3192 1.93077 40.25 4.3125 40.25H41.6875C44.0692 40.25 46 38.3192 46 35.9375V19.6914L23.3704 25.726C23.1277 25.7907 22.8723 25.7907 22.6296 25.726L0 19.6914V35.9375Z" fill="black"/>
        </svg>
        </a>

        <div class="col-md-4 mb-0">
            {% if user.is_authenticated %}
                <div class="text-end" style="margin-top: 10px;">
                    <a href="{% if user_side == 'employee' %}{% url 'employer:home-employer' %}{% else %}{% url 'employee:home-employee' %}{% endif %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-primary me-2">{% if user_side == 'employee' %}Employer{% else %}Employee{% endif %}</button></a>
                    <a href="{% url 'users:logout' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-danger me-2">Logout</button></a>
                </div>
            {% else %}
                <div class="text-end" style="margin-top: 10px;">
                    <a href="{% url 'users:login' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-primary">Login</button></a>
                    <a href="{% url 'users:register' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-success">Register</button></a>
                </div>
            {% endif %}
        </div>

    </div>

</body>
</html>

A_SearchJob/templates/story/messages_logic.html
{% block page_content %}
    {% if messages %}
        <div class="row" style="width: 40%; margin-top:10px; margin-left: 30%; text-align: center;">
            <div class="col-sm-20">
                <div class="thumbnail" style="border-radius: 15px; border: 3px solid rgb(43,145,203); box-shadow: 6px 6px 7px rgb(112,109,213); background-color: rgb(207,224,252)">
                    <div class="caption" style="padding: 10px;">
                        <div class="messages" style="">
                            {% for message in messages %}
                                <span {% if message.tags %} class="{{ message.tags }}" {% endif %} style="font-family: 'JetBrains Mono Medium'; color: #4e87ff; font-size: 20px;">
                                    {% if 'html_safe' in message.tags %}{{ message|safe }}
                                    {% else %}{{ message }}{% endif %}
                                </span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock page_content %}

A_SearchJob/templates/story/own_stories.html
{% extends 'story/base_story_block.html' %}

{% block add_in_nav %}
    <div class="text-end" style="margin-right: 10px; margin-top: 10px;">
        <a href="{% if user_side == 'employee' %}{% url 'employer:home-employer' %}{% else %}{% url 'employee:home-employee' %}{% endif %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-primary me-2">{% if user_side == 'employee' %}Employer{% else %}Employee{% endif %}</button></a>
        <a href="{% url 'users:logout' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-danger me-2">Logout</button></a>
    </div>
{% endblock add_in_nav %}

{% block main_content %}

    {% if not count_of_stories %}
        <div style="margin-left: 36%; margin-top: 10%;">
            <h1>You have not created any resume yet.</h1>
            <h1>To create, click <a href="{% url 'story:story-create' %}">here</a></h1>
        </div>
    {% endif %}


    <div class="col-sm-8 col-sm-offset-2" style="margin-top: 50px; margin-bottom: 20px;">
        {% for story in own_stories %}
            <div class="row">
                <div class="col-sm-20" style="margin-bottom: 20px;">
                    <div class="thumbnail" style="border-radius: 10px; border: 3px solid rgba(130,196,15,0.85); box-shadow: 8px 8px 14px rgba(188,211,68,0.92);">
                        <div class="caption" style="padding: 25px;">

                            <div style="margin-bottom: 20px;">
                                <p style="text-align: center; font-size: 30px; font-weight: 500; color: #fd9626">{{ story.headline }}</p>
                            </div>


                            <div style="display: flex; justify-content: space-between; margin-bottom: 30px;">
                                <div style="margin-left: 15%; margin-top: 7px;">
                                    <a href="{{ story.get_url_to_story }}" style="text-decoration: none; font-size: 22px; color: #d77500; font-weight: 500;">The whole story</a>
                                </div>
                                <div style="margin-top: 7px;">
                                    <a href="{% url 'story:story-delete' story.id %}" style="text-decoration: none; font-size: 22px; color: #ff1010; font-weight: 500; ">Delete</a>
                                </div>
                                <div style="margin-right: 15%; margin-top: 7px;">
                                    <a href="{{ story.get_url_to_update_story }}" style="text-decoration: none; font-size: 22px; color: #d77500; font-weight: 500;">Update</a>
                                </div>
                            </div>

                            <p style="font-size: 20px; margin-bottom: 20px; color: #256996; padding-left: 5%">
                                {{ story.title }}
                            </p>

                            <p style="width: 100%; overflow: hidden; margin-top: 20px; font-weight: 400; font-size: 20px; margin-left: 20px;">
                                <span style="padding-left: 30px;">User: {{ story.user }}</span>
                                <span style="margin-left: 45%;">Useful for {{ story.for_who }}</span>
                            </p>
                            <hr>
                            <p style="display: flex; justify-content: space-between; font-size: 17px; margin-top: 15px; color: rgba(119,13,72,0.75)">
                                <span>Latest update: {{ story.update|timesince }} тому</span>
                                <span>Published: {{ story.timestamp|timesince }} тому</span>
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock main_content %}

A_SearchJob/templates/story/story_creation.html
{% extends 'story/base_story_block.html' %}

{% block add_in_nav %}

    <div class="text-end" style="margin-right: 10px; margin-top: 10px;">
        <a href="{% if user_side == 'employee' %}{% url 'employer:home-employer' %}{% else %}{% url 'employee:home-employee' %}{% endif %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-primary me-2">{% if user_side == 'employee' %}Employer{% else %}Employee{% endif %}</button></a>
        <a href="{% url 'users:logout' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-danger me-2">Logout</button></a>
    </div>

{% endblock add_in_nav %}

{% block main_content %}

    <div class="col-sm-6 col-sm-offset-3" style="margin-bottom: 10px; margin-top: 50px;">
        <div class="row">
            <div class="col-sm-20">
                <div class="thumbnail" style="box-shadow: 6px 6px 14px #ffcc6c; border-radius: 10px; border: 3px solid #ffcc6c;">
                    <div class="caption" style="padding: 25px;">

                        <h2 style="text-align: center; font-size: 35px; margin-bottom: 25px; font-weight: 500; color: #14d942">Your story</h2>
                        <hr style="color: #0d6efc; height: 2px;">

                        <form action="" method="POST" enctype="multipart/form-data">
                            {% csrf_token %}

                            <table style="margin-left: 25px; margin-right: 25px; margin-bottom: 30px;">
                                <tr>
                                    <td>
                                        <div class="headline-input" style="margin-top: 30px;">
                                            <label style="margin-left: 7%; color: #0d6efc; font-size: 18px; margin-bottom: 5px;" for="id_headline">Headline</label>
                                            <input class="form-control" style="height: 40px; color: #0d6efc; border: 3px solid #62d91b; border-radius: 10px; box-shadow: 5px 5px 14px #24e159;
                                             font-size: 18px; padding: 15px; margin-bottom: 30px;" type="text" name="headline" maxlength="200" required="" value="{{ headline }}" id="id_headline">
                                        </div>
                                    </td>
                                    <td rowspan="4">
                                        <div class="text-input" style="margin-left: 50px; margin-bottom: 30px; margin-top: 30px;">
                                            <label style="margin-left: 7%; color: #0d6efc; font-size: 20px; margin-bottom: 5px;" for="id_text">Content</label>
                                            <textarea class="form-control" style="border-radius: 10px; color: #0d6efc; border: 3px solid #62d91b; box-shadow: 5px 5px 14px #24e159; font-size: 16px; padding: 15px;" id="id_text" name="text" rows="12" cols="50">{{ text }}</textarea>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="title-input">
                                            <label style="margin-left: 7%; color: #0d6efc; font-size: 18px; margin-bottom: 5px;" for="id_title">Title</label>
                                            <textarea class="form-control" style="color: #0d6efc; border: 3px solid #62d91b; border-radius: 10px; box-shadow: 5px 5px 14px #24e159; margin-bottom: 30px; font-size: 18px; padding: 15px;" id="id_title" name="title" rows="3" cols="20">{{ title }}</textarea>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="for_who_input">
                                            <label style="margin-left: 4%; color: #0d6efc; font-size: 18px; margin-bottom: 5px; margin-right: 15px;" for="id_for_who">For </label>

                                            <select name="for_who" id="id_for_who" style="margin-bottom: 25px; font-weight: 500; font-size: 18px; padding: 5px; height: 40px; border: 3px solid #62d91b; border-radius: 10px; color: #0d6efc">
                                                <option value="employers">employers</option>
                                                <option value="employees">employees</option>
                                                <option value="everyone" selected="">everyone</option>
                                            </select>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="comments_input">
                                            <label style="margin-left: 4%; color: #0d6efc; margin-right: 20px; font-size: 18px; margin-bottom: 5px;" for="id_comments">Comments</label>
                                            <input type="checkbox" style="width: 18px; height: 18px; margin-top: 5px; color: #62d91b" name="comments" id="id_comments" {% if comments %}checked{% endif %}>
                                        </div>
                                    </td>
                                </tr>
                            </table>

                            <input type="submit" class="btn btn-primary" value="{{ text_for_btn }}" style="font-size: 30px; padding-top: 0; font-weight: 500; width: 100%; height: 50px; border-radius: 10px; border: 2px solid #858DF5; box-shadow: 10px 10px 10px #858DF5;">
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock main_content %}