A_SearchJob/A_SearchJob/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('employer/', include('employer.urls'), name='home-employer'),
    path('employee/', include('employee.urls'), name='home-employee'),
    path('story/', include('story.urls'), name='home-story'),

    path('', include('employee.urls'), name='home'),

    path('users/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A_SearchJob/employee/urls.py
from django.urls import path
from employee.views import home, create_resume, update_resume, delete_resume, \
    liked_vacancies, own_resumes, vacancy, resume, like_vacancy, respond_to_vacancy

app_name = 'employee'

urlpatterns = [
    path('', home, name='home-employee'),
    path('create/', create_resume, name='create'),
    path('update/<int:id>/', update_resume, name='update'),
    path('delete/<int:id>/', delete_resume, name='delete'),

    path('liked/', liked_vacancies, name='liked'),
    path('resumes/', own_resumes, name='resumes'),

    path('vacancy/<int:id>/', vacancy, name='vacancy'),
    path('resume/<int:id>/', resume, name='resume'),
    path('like_vacancy/<int:id>/', like_vacancy, name='like_vacancy'),

    path('respond/<int:id>/', respond_to_vacancy, name='respond')
]

A_SearchJob/employer/urls.py
from django.urls import path
from employer.views import home, create_vacancy, update_vacancy, delete_vacancy, \
    liked_resumes, own_vacancies, resume, vacancy, like_resume, respond_to_resume

app_name = 'employer'

urlpatterns = [
    path('', home, name='home-employer'),
    path('create/', create_vacancy, name='create'),
    path('update/<int:id>/', update_vacancy, name='update'),
    path('delete/<int:id>/', delete_vacancy, name='delete'),

    path('vacancy/<int:id>/', vacancy, name='vacancy'),
    path('resume/<int:id>/', resume, name='resume'),
    path('like_resume/<int:id>/', like_resume, name='like_resume'),

    path('liked/', liked_resumes, name='liked'),
    path('vacancies/', own_vacancies, name='vacancies'),

    path('respond/<int:id>/', respond_to_resume, name='respond')
]

A_SearchJob/story/urls.py
from django.urls import path
from .views import home, create_story, update_story, delete_story, \
    own_stories, delete_comment, like_story, liked_stories, story_content

app_name = 'story'

urlpatterns = [
    path('', home, name='home-story'),
    path('<int:id>/', story_content, name='story-content'),

    path('create/', create_story, name='story-create'),
    path('update/<int:id>/', update_story, name='story-update'),
    path('delete/<int:id>/', delete_story, name='story-delete'),

    path('liked_stories/', liked_stories, name='stories-liked'),
    path('own_stories/', own_stories, name='story-own'),

    path('delete_comment/<int:id>/', delete_comment, name='story-delete-comment'),
    path('like_story/<int:id>/', like_story, name='story-like')
]

A_SearchJob/users/urls.py
from django.urls import path, include
from users.views import register

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register')
]

A_SearchJob/employee/forms.py
from django import forms

from employee.models import EmployeeModel

from datetime import datetime
from django.utils.timezone import make_aware
from django.forms import TextInput, MultiWidget, DateTimeField


class MinimalSplitDateTimeMultiWidget(MultiWidget):

    def __init__(self, widgets=None, attrs=None):
        if widgets is None:
            if attrs is None:
                attrs = {}
            date_attrs = attrs.copy()

            date_attrs['type'] = 'date'

            widgets = [
                TextInput(attrs=date_attrs)
            ]
        super().__init__(widgets, attrs)

    def decompress(self, value):
        if value:
            return [value, value.strftime('%H:%M')]
        return [None, None]

    def value_from_datadict(self, data, files, name):
        date_str = super().value_from_datadict(data, files, name)[0]

        if date_str == '':
            return None

        my_datetime = datetime.strptime(date_str, "%Y-%m-%d")

        return make_aware(my_datetime)


class EmployeeForm(forms.ModelForm):

    birth = DateTimeField(widget=MinimalSplitDateTimeMultiWidget())

    class Meta:
        model = EmployeeModel

        fields = [
            'name',
            'birth',
            'address',
            'phone_number',

            'link_to_own_website',
            'linkedin',
            'github',
            'email',

            'level_of_english',
            'main_programming_language',
            'desired_salary',
            'type_of_job',

            'description_about_yourself',
            'education',
            'hard_skills',
            'work_experience',
            'soft_skills',

            'image',
            'additional_files'
        ]

A_SearchJob/employee/views.py
from django.shortcuts import render, get_object_or_404, redirect
from additional_functions.additional import paginator_array, split_lines, set_width_height_for_image, get_current_year
from employee.models import EmployeeModel
from employer.models import EmployerModel
from users.models import User
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from employee.forms import EmployeeForm
from django.conf import settings
from django.contrib import messages

from django.core.mail import EmailMessage
from django.template.loader import render_to_string

import json


def home(request):

    if not str(request.get_full_path()).replace('/', ''):
        return redirect('employee:home-employee')

    settings.USER_SIDE = 'employee'

    queryset = EmployerModel.objects.all()

    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(name_of_job__icontains=query) |
            Q(location__icontains=query) |
            Q(name_of_company__icontains=query) |
            Q(type_of_job__icontains=query) |
            Q(main_programming_language__icontains=query)
        )

    vacancies_per_page = 4
    paginator = Paginator(queryset, vacancies_per_page)

    page_request_var = 'page'
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.get_page(page)
    except PageNotAnInteger:
        queryset = paginator.page(paginator.num_pages)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'vacancies': queryset,
        'page_request_var': page_request_var,
        'paginator_range': paginator_array(paginator.num_pages, paginator.get_page(page).number),
        'count_of_pages': paginator.num_pages,
        'count_of_vacancies': len(queryset),
        'current_year': get_current_year()
    }

    return render(request, 'employee/home.html', context)


def create_resume(request):
    form = EmployeeForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        resume_ins = form.save(commit=False)
        resume_ins.user = request.user
        resume_ins.save()

        extra_tags = 'html_safe'

        message = f'<p>The <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/employee/resume/{resume_ins.id}/">resume</a> was successfully created!</p>' \
                  f'<p>To update your resume, click <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/employee/update/{resume_ins.id}/">here</a></p>'

        messages.info(request, message, extra_tags)

        return redirect('employee:resumes')

    context = {
        'form': form,
        'text_for_btn': 'Create resume',
        'current_year': get_current_year()
    }

    return render(request, 'employee/resume_creation.html', context)


def update_resume(request, id=None):

    resume_ins = get_object_or_404(EmployeeModel, id=id)
    form = EmployeeForm(request.POST or None, request.FILES or None, instance=resume_ins)

    if form.is_valid():
        resume_ins = form.save(commit=False)
        resume_ins.save()

        extra_tags = 'html_safe'
        message = f'<p>The <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/employee/resume/{resume_ins.id}/">resume</a> was successfully updated!</p>' \
                  f'<p>To update again your resume, click <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/employee/update/{resume_ins.id}/">here</a></p>'

        messages.info(request, message, extra_tags)

        return redirect('employee:resumes')

    context = {
        'form': form,
        'text_for_btn': 'Update resume',
        'current_year': get_current_year()
    }

    return render(request, 'employee/resume_creation.html', context)


def delete_resume(request, id=None):
    resume_instance = get_object_or_404(EmployeeModel, id=id)
    resume_instance.delete()

    extra_tags = 'html_safe'
    message = f'<p>Resume has just been successfully deleted!</p>'

    messages.info(request, message, extra_tags)

    return redirect('employee:resumes')


def liked_vacancies(request):
    user = get_object_or_404(User, id=request.user.id)

    with open('additional_files/liked_vacancies.json', "r") as file:
        data = json.load(file)

    user_id = str(user.id)

    try:
        liked_vacancies_user = data['users'][user_id]
        queryset = EmployerModel.objects.all().filter(id__in=liked_vacancies_user)
    except KeyError:
        queryset = EmployerModel.objects.all().filter(id__in=[0])

    query = request.GET.get('q_liked_v')
    if query:
        queryset = queryset.filter(
            Q(name_of_job__icontains=query) |
            Q(location__icontains=query) |
            Q(name_of_company__icontains=query) |
            Q(type_of_job__icontains=query) |
            Q(main_programming_language__icontains=query)
        )

    context = {
        'vacancies': queryset,
        'count_of_vacancies': len(queryset),
        'add_query': False,
        'current_year': get_current_year()
    }

    if query:
        context['add_query'] = True
    else:
        context['add_query'] = False

    return render(request, 'employee/liked_vacancies.html', context)


def own_resumes(request):
    queryset = [resume for resume in EmployeeModel.objects.all() if resume.user == request.user]
    context = {
        'resumes': queryset,
        'count_of_resumes': len(queryset),
        'current_year': get_current_year()
    }

    return render(request, 'employee/own_resumes.html', context)


def like_vacancy(request, id=None):

    vacancy_obj = get_object_or_404(EmployerModel, id=id)

    if request.user.is_authenticated:
        user = get_object_or_404(User, id=request.user.id)

        user_id = str(user.id)
        vacancy_id = vacancy_obj.id

        with open('additional_files/liked_vacancies.json', "r") as file:
            data = json.load(file)

        if user_id in data['users']:
            if vacancy_id in data['users'][user_id]:
                data['users'][user_id].remove(vacancy_id)
            else:
                data['users'][user_id].append(vacancy_id)
        else:
            data['users'][user_id] = [vacancy_id]

        with open('additional_files/liked_vacancies.json', 'w') as file:
            json.dump(data, file)

    return redirect(f'/employee/vacancy/{vacancy_obj.id}/')


def vacancy(request, id=None):

    vacancy_obj = get_object_or_404(EmployerModel, id=id)

    context = {
        'vacancy': vacancy_obj,
        'requirements': split_lines(vacancy_obj.requirements_of_job),
        'benefits': split_lines(vacancy_obj.benefits_of_job),
        'responsibilities': split_lines(vacancy_obj.responsibilities_of_job),
        'current_year': get_current_year()
    }

    if request.user.is_authenticated:
        user = get_object_or_404(User, id=request.user.id)
        context['user_main'] = user

        with open('additional_files/liked_vacancies.json', "r") as file:
            data = json.load(file)

        user_id = str(user.id)

        try:
            if vacancy_obj.id in data['users'][user_id]:
                context['existence_in_liked_vacancies'] = True
            else:
                context['existence_in_liked_vacancies'] = False
        except KeyError:
            context['existence_in_liked_vacancies'] = False

    return render(request, 'employee/vacancy.html', context)


def resume(request, id=None):

    resume_obj = get_object_or_404(EmployeeModel, id=id)
    size_of_image = set_width_height_for_image(resume_obj.width_field, resume_obj.height_field)

    context = {
        'resume': resume_obj,
        'image_width': size_of_image[0],
        'image_height': size_of_image[1],
        'soft_skills': split_lines(resume_obj.soft_skills),
        'hard_skills': split_lines(resume_obj.hard_skills),
        'user': request.user,
        'current_year': get_current_year()
    }

    if resume_obj.image:
        context['image_existence'] = True
    else:
        context['image_existence'] = False

    return render(request, 'employee/resume.html', context)


def respond_to_vacancy(request, id=None):

    if not request.user.is_authenticated:
        return redirect('users:login')

    vacancy_obj = get_object_or_404(EmployerModel, id=id)
    user_obj = get_object_or_404(User, id=request.user.id)

    queryset_of_appropriate_resumes = EmployeeModel.objects.all().filter(user=user_obj)
    number_of_resumes = len(queryset_of_appropriate_resumes)

    subject = 'Response to the vacancy'
    from_email = settings.EMAIL_HOST_USER
    to = vacancy_obj.email

    # for local site
    prefix_for_url = 'http://127.0.0.1:8000'

    context_for_email = {
        'subject': subject,
        'vacancy': vacancy_obj,
        'resumes': queryset_of_appropriate_resumes,
        'number_of_resumes': number_of_resumes,
        'prefix': prefix_for_url
    }

    if queryset_of_appropriate_resumes:
        id_for_resume = [obj_id.id for obj_id in queryset_of_appropriate_resumes]
        emails = list(set([obj.email for obj in queryset_of_appropriate_resumes]))
        phone_numbers = list(set([obj.phone_number for obj in queryset_of_appropriate_resumes]))

        if number_of_resumes == 1:
            context_for_email['id_for_resume'] = id_for_resume[0]
            context_for_email['email'] = emails[0]
            context_for_email['phone_number'] = phone_numbers[0]
        else:
            context_for_email['id_for_resume'] = id_for_resume
            context_for_email['email'] = emails
            context_for_email['phone_number'] = phone_numbers

    html_content = render_to_string('employee/email_content.html', context_for_email)

    msg = EmailMessage(subject, html_content, from_email, [to])
    msg.content_subtype = "html"
    msg.send()

    extra_tags = 'html_safe'

A_SearchJob/templates/employee/liked_vacancies.html
{% extends 'employee/base_employee_block.html' %}

{% block add_in_nav %}

    <ul class="nav col-12 col-md-6 me-lg-auto mb-2 justify-content-center mb-md-0" style="font-size: 25px;">
        <li><a href="{% url 'employee:home-employee' %}" class="nav-link px-2">Home</a></li>
        <li><a href="{% url 'employee:create' %}" class="nav-link px-2">Create</a></li>
        <li><a href="{% url 'employee:resumes' %}" class="nav-link px-2">My resumes</a></li>
        <li><a href="{% url 'employee:liked' %}" class="nav-link px-2 link-secondary">Liked</a></li>
        <li><a href="{% url 'story:home-story' %}" class="nav-link px-2">Stories</a></li>
    </ul>

    <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3" style="display: flex;" action="" method="GET">
        <input type="text" style="margin-right: 7px; height: 40px; font-size: 20px; margin-top: 8px; border-radius: 10px;" name="q_liked_v" class="form-control" placeholder="Search vacancy..." aria-label="Search" value="{{ request.GET.q_liked_v }}">
        <input type="submit" style="font-size: 20px; margin-top: 8px; border-radius: 10px;" value="Search" class="btn btn-outline-primary me-2">
    </form>

{% endblock add_in_nav %}

{% block main_content %}

    {% if not count_of_vacancies %}
        {% if not add_query %}
            <div style="margin-left: 31%; margin-top: 5%;">
                <h1 style="font-size: 35px;">You have not liked any vacancy yet.</h1>
            </div>
        {% else %}
            <div class="col-sm-6 col-sm-offset-3" style="margin-top: 100px;">
                <p style="font-size: 35px;"><b>Nothing was found for your request "{{ request.GET.q_liked_v }}"</b></p>
                <p style="font-size: 30px;">Try changing the query</p>
            </div>
        {% endif %}
    {% endif %}


    <div class="col-sm-8 col-sm-offset-2" style="margin-top: 50px; margin-bottom: 20px;">
        {% for vacancy in vacancies %}
            <div class="row">
                <div class="col-sm-20" style="margin-bottom: 20px;">
                    <div class="thumbnail" style="border-radius: 10px; border: 3px solid rgba(130,196,15,0.85); box-shadow: 8px 8px 14px rgba(188,211,68,0.92);">
                        <div class="caption" style="padding: 25px;">

                            <div style="margin-bottom: 10px; text-align: center;">
                                <a href="{{ vacancy.get_url_to_vacancy }}" style="text-decoration: none; font-size: 28px; font-weight: 500; color: #fd9626">{{ vacancy.type_of_job }}</a>
                            </div>

                            <p style="width: 100%; overflow: hidden; margin-top: 20px; font-weight: 400; font-size: 20px; margin-left: 20px;">
                                <span style="padding-right: 200px; font-size: 23px; font-weight: 500;">{{ vacancy.name_of_company }}</span>
                                <span>{{ vacancy.main_programming_language }}</span>
                                <span style="float: right; margin-right: 50px; margin-top: 2px;">{{ vacancy.name_of_job }}</span>
                            </p>
                            <hr>
                            <p style="font-size: 20px; margin-left: 20px; color: #888888">Published: {{ vacancy.timestamp|timesince }} тому</p>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock main_content %}

A_SearchJob/templates/employee/login_in_nav.html
<div style="margin-top: 10px;">
    {% if user.is_authenticated %}
        <div class="text-end" style="margin-right: 10px;">
            <a href="{% url 'employer:home-employer' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-primary me-2">Employer</button></a>
            <a href="{% url 'users:logout' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-danger me-2">Logout</button></a>
        </div>
    {% else %}
        <div class="text-end" style="margin-right: 10px;">
            <a href="{% url 'users:login' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-primary">Login</button></a>
            <a href="{% url 'users:register' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-success">Register</button></a>
        </div>
    {% endif %}
</div>

A_SearchJob/templates/employee/messages_logic.html
{% block page_content %}
    {% if messages %}
        <div class="row" style="width: 40%; margin-top:10px; margin-left: 30%; text-align: center;">
            <div class="col-sm-20">
                <div class="thumbnail" style="border-radius: 15px; border: 3px solid rgb(43,145,203); box-shadow: 6px 6px 7px rgb(112,109,213); background-color: rgb(207,224,252)">
                    <div class="caption" style="padding: 10px;">
                        <div class="messages" style="">
                            {% for message in messages %}
                                <span {% if message.tags %} class="{{ message.tags }}" {% endif %} style="font-family: 'JetBrains Mono Medium'; color: #4e87ff; font-size: 20px;">
                                    {% if 'html_safe' in message.tags %}{{ message|safe }}
                                    {% else %}{{ message }}{% endif %}
                                </span>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock page_content %}

A_SearchJob/templates/employee/own_resumes.html
{% extends 'employee/base_employee_block.html' %}

{% block add_in_nav %}

    <ul class="nav col-12 col-md-6 me-lg-auto mb-2 justify-content-center mb-md-0" style="font-size: 25px;">
        <li><a href="{% url 'employee:home-employee' %}" class="nav-link px-2">Home</a></li>
        <li><a href="{% url 'employee:create' %}" class="nav-link px-2">Create</a></li>
        <li><a href="{% url 'employee:resumes' %}" class="nav-link px-2 link-secondary">My resumes</a></li>
        <li><a href="{% url 'employee:liked' %}" class="nav-link px-2">Liked</a></li>
        <li><a href="{% url 'story:home-story' %}" class="nav-link px-2">Stories</a></li>
    </ul>

    {% include 'employee/login_in_nav.html' %}

{% endblock add_in_nav %}

{% block main_content %}

    {% if not count_of_resumes %}
        <div style="margin-left: 36%; margin-top: 15%;">
            <h1>You have not created any resume yet.</h1>
            <h1>To create, click <a href="{% url 'employee:create' %}">here</a></h1>
        </div>
    {% endif %}


    <div class="col-sm-8 col-sm-offset-2" style="margin-top: 50px; margin-bottom: 20px;">
        {% for resume in resumes %}
            <div class="row">
                <div class="col-sm-20" style="margin-bottom: 20px;">
                    <div class="thumbnail" style="border-radius: 10px; border: 3px solid rgba(130,196,15,0.85); box-shadow: 8px 8px 14px rgba(188,211,68,0.92);">
                        <div class="caption" style="padding: 25px;">
                            <div style="display: flex; justify-content: space-between;">
                                <div style="margin-left: 2%; margin-top: 7px;">
                                    <a href="{{ resume.get_url_to_whole_resume }}" style="text-decoration: none; font-size: 22px; color: #d77500; font-weight: 500;">The whole resume</a>
                                </div>
                                <div style="margin-bottom: 10px;">
                                    <p style="text-align: center; font-size: 28px; font-weight: 500; color: #fd9626">{{ resume.type_of_job }}</p>
                                </div>
                                <div style="margin-right: 2%; margin-top: 7px;">
                                    <a href="{{ resume.get_url_to_resume }}" style="text-decoration: none; font-size: 22px; color: #d77500; font-weight: 500;">Update</a>
                                </div>
                            </div>

                            <p style="width: 100%; overflow: hidden; margin-top: 20px; font-weight: 400; font-size: 20px; margin-left: 20px;">
                                <span style="padding-right: 100px;">{{ resume.name }}</span>
                                <span style="padding-right: 100px;">{{ resume.birth }}</span>
                                <span>{{ resume.phone_number }}</span>
                                <span style="float: right; margin-bottom: 15px; margin-right: 50px; font-weight: 500;">{{ resume.main_programming_language }}</span>
                            </p>
                            <hr>
                            <p style="display: flex; justify-content: space-between; font-size: 17px; margin-top: 15px; color: rgba(119,13,72,0.75)">
                                <span>Latest update: {{ resume.update|timesince }} тому</span>
                                <a href="{% url 'employee:delete' resume.id %}" style="text-decoration: none; font-size: 22px; color: #ff1010; font-weight: 500; ">Delete</a>
                                <span>Published: {{ resume.timestamp|timesince }} тому</span>
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock main_content %}

A_SearchJob/templates/employee/resume.html
{% extends 'employee/base_employee_block.html' %}

{% block add_in_nav %}

    <ul class="nav col-12 col-md-6 me-lg-auto mb-2 justify-content-center mb-md-0" style="font-size: 25px;">
        <li><a href="{% url 'employee:home-employee' %}" class="nav-link px-2">Home</a></li>
        <li><a href="{% url 'employee:create' %}" class="nav-link px-2">Create</a></li>
        <li><a href="{% url 'employee:resumes' %}" class="nav-link px-2 link-secondary">My resumes</a></li>
        <li><a href="{% url 'employee:liked' %}" class="nav-link px-2">Liked</a></li>
        <li><a href="{% url 'story:home-story' %}" class="nav-link px-2">Stories</a></li>
    </ul>

    {% include 'employee/login_in_nav.html' %}

{% endblock add_in_nav %}

{% block main_content %}

    <div class="col-sm-8 col-sm-offset-2" style="margin-bottom: 30px; margin-top: 50px;">
        <div class="row">
            <div class="col-sm-20">
                <div class="thumbnail" style="padding: 0; border-radius: 10px; border: 3px solid rgba(178,178,178,0.79); box-shadow: 10px 10px 14px rgba(159,159,159,0.57); display: flex;">
                    <div style="flex: 29%; text-align: center; background-color: aqua; padding: 20px;">
                        {% if image_existence %}
                            <img style="border-radius: 50px; margin-bottom: 20px;" src="{{ resume.image.url }}" width="{{ image_width }}px" height="{{ image_height }}px" alt="Photo of person">
                        {% endif %}

                        <div style="text-align: left;">
                            <h2>Personal information</h2>
                            <hr style="height: 2px; margin-bottom: 20px;">
                            <div>
                                <h4>Name</h4>
                                <p>{{ resume.name }}</p>
                            </div>
                            <div>
                                <h4>Date of birth</h4>
                                <p>{{ resume.birth }}</p>
                            </div>
                            <div style="margin-bottom: 20px;">
                                <h4>Address</h4>
                                <p>{{ resume.address }}</p>
                            </div>

                            <h2>Additional Information</h2>
                            <hr style="height: 2px; margin-bottom: 20px;">
                            <div>
                                <h4>English level</h4>
                                <p>{{ resume.level_of_english }}</p>
                            </div>
                            <div>
                                <h4>Main programming language</h4>
                                <p>{{ resume.main_programming_language }}</p>
                            </div>

                            <h2>Hard skills</h2>
                            <hr style="height: 2px; margin-bottom: 20px;">
                            <ul style="margin-bottom: 20px;">
                                {% for skills in hard_skills %}
                                    <li>{{ skills }}</li>
                                {% endfor %}
                            </ul>
                        </div>

                    </div>

                    <div style="background-color: rgba(178,178,178,0.79); flex: 1px;"></div>

                    <div style="flex: 70%; text-align: left; padding: 10px 20px;">

                        <h1 style="font-size: 35px;">{{ resume.name }}</h1>
                        <hr style="height: 2px;">
                        <p style="font-weight: 500; margin-bottom: 30px;">{{ resume.description_about_yourself }}</p>

                        <h2 style="margin-bottom: 10px;">Work experience</h2>
                        <hr style="height: 2px;">
                        <p style="margin-bottom: 20px;">{{ resume.work_experience }}</p>

                        <h2 style="margin-bottom: 10px;">Education and qualification</h2>
                        <hr style="height: 2px;">
                        <p style="margin-bottom: 20px;">{{ resume.education }}</p>

                        <h2 style="margin-bottom: 10px;">Type of work</h2>
                        <hr style="height: 2px;">
                        <p>{{ resume.type_of_job }}</p>
                        <p style="margin-bottom: 20px;">Desired salary: {{ resume.desired_salary }}$ per month</p>

                        <h2 style="margin-bottom: 10px;">Soft skills</h2>
                        <hr style="height: 2px;">
                        <ul style="margin-bottom: 20px;">
                            {% for skill in soft_skills %}
                                <li>{{ skill }}</li>
                            {% endfor %}
                        </ul>

                        <h2 style="margin-bottom: 10px;">Links to the author</h2>
                        <hr style="height: 2px;">
                        <div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
                            {% if resume.link_to_own_website %}
                                <a href="{{ resume.link_to_own_website }}" target="_blank" style="text-decoration: none; color: #5295e5; font-weight: 500; font-size: 15px; margin-left: 25px;">Own site</a>
                            {% endif %}

                            {% if resume.linkedin %}
                                <a href="{{ resume.linkedin }}" target="_blank" style="text-decoration: none; color: #5295e5; font-weight: 500; font-size: 15px;">LinkedIn</a>
                            {% endif %}

                            {% if resume.github %}
                                <a href="{{ resume.github }}" target="_blank" style="text-decoration: none; color: #5295e5; font-weight: 500; font-size: 15px; margin-right: 25px;">GitHub</a>
                            {% endif %}
                        </div>

                        {% if resume.additional_files %}
                            <h2 style="margin-bottom: 10px;">Additional file</h2>
                            <hr style="height: 2px;">
                            <a target="_blank" href="{{ resume.additional_files.url }}" style="text-decoration: none; color: #5295e5; font-weight: 500; font-size: 15px; margin-left: 25px; margin-bottom: 20px;">File</a>
                        {% endif %}

                        <hr style="height: 2px">
                        <p style="display: flex; justify-content: space-between; font-size: 15px; margin-right: 15px; text-align: right; font-weight: 200">
                            {{ resume.timestamp|timesince }} тому
                            {% if user.is_superuser or user == resume.user %}
                                <a href="{% url 'employee:delete' resume.id %}"><button class="btn btn-outline-danger" id="delete" style="font-size: 15px; font-weight: 700; width: 100px; border-radius: 10px; border: 3px solid #d20f3e;">Delete</button></a>
                            {% endif %}
                        </p>

                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock main_content %}