A_SearchJob/A_SearchJob/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    path('employer/', include('employer.urls'), name='home-employer'),
    path('employee/', include('employee.urls'), name='home-employee'),
    path('story/', include('story.urls'), name='home-story'),

    path('', include('employee.urls'), name='home'),

    path('users/', include('users.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

A_SearchJob/employee/urls.py
from django.urls import path
from employee.views import home, create_resume, update_resume, delete_resume, \
    liked_vacancies, own_resumes, vacancy, resume, like_vacancy, respond_to_vacancy

app_name = 'employee'

urlpatterns = [
    path('', home, name='home-employee'),
    path('create/', create_resume, name='create'),
    path('update/<int:id>/', update_resume, name='update'),
    path('delete/<int:id>/', delete_resume, name='delete'),

    path('liked/', liked_vacancies, name='liked'),
    path('resumes/', own_resumes, name='resumes'),

    path('vacancy/<int:id>/', vacancy, name='vacancy'),
    path('resume/<int:id>/', resume, name='resume'),
    path('like_vacancy/<int:id>/', like_vacancy, name='like_vacancy'),

    path('respond/<int:id>/', respond_to_vacancy, name='respond')
]

A_SearchJob/employer/urls.py
from django.urls import path
from employer.views import home, create_vacancy, update_vacancy, delete_vacancy, \
    liked_resumes, own_vacancies, resume, vacancy, like_resume, respond_to_resume

app_name = 'employer'

urlpatterns = [
    path('', home, name='home-employer'),
    path('create/', create_vacancy, name='create'),
    path('update/<int:id>/', update_vacancy, name='update'),
    path('delete/<int:id>/', delete_vacancy, name='delete'),

    path('vacancy/<int:id>/', vacancy, name='vacancy'),
    path('resume/<int:id>/', resume, name='resume'),
    path('like_resume/<int:id>/', like_resume, name='like_resume'),

    path('liked/', liked_resumes, name='liked'),
    path('vacancies/', own_vacancies, name='vacancies'),

    path('respond/<int:id>/', respond_to_resume, name='respond')
]

A_SearchJob/story/urls.py
from django.urls import path
from .views import home, create_story, update_story, delete_story, \
    own_stories, delete_comment, like_story, liked_stories, story_content

app_name = 'story'

urlpatterns = [
    path('', home, name='home-story'),
    path('<int:id>/', story_content, name='story-content'),

    path('create/', create_story, name='story-create'),
    path('update/<int:id>/', update_story, name='story-update'),
    path('delete/<int:id>/', delete_story, name='story-delete'),

    path('liked_stories/', liked_stories, name='stories-liked'),
    path('own_stories/', own_stories, name='story-own'),

    path('delete_comment/<int:id>/', delete_comment, name='story-delete-comment'),
    path('like_story/<int:id>/', like_story, name='story-like')
]

A_SearchJob/users/urls.py
from django.urls import path, include
from users.views import register

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', register, name='register')
]

A_SearchJob/employer/forms.py
from django import forms
from employer.models import EmployerModel


class EmployerForm(forms.ModelForm):

    class Meta:
        model = EmployerModel

        fields = [
            'name_of_job',
            'name_of_company',
            'location',

            'required_english',
            'type_of_job',
            'main_programming_language',

            'lower_salary',
            'higher_salary',

            'remote_job',
            'min_experience',

            'benefits_of_job',
            'responsibilities_of_job',
            'requirements_of_job',

            'time_work',
            'link_to_own_website',
            'linkedin',
            'email',
            'phone_number'
        ]

A_SearchJob/employer/views.py
from django.shortcuts import render, get_object_or_404, redirect
from additional_functions.additional import paginator_array, split_lines, set_width_height_for_image, get_current_year

from employee.models import EmployeeModel
from employer.models import EmployerModel
from users.models import User

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db.models import Q
from employer.forms import EmployerForm

from django.contrib import messages
from django.conf import settings

from django.core.mail import EmailMessage
from django.template.loader import render_to_string

import json


def home(request):

    settings.USER_SIDE = 'employer'

    queryset = EmployeeModel.objects.all()

    query = request.GET.get('q_resumes')
    if query:
        queryset = queryset.filter(
            Q(name__icontains=query) |
            Q(main_programming_language__icontains=query) |
            Q(type_of_job__icontains=query) |
            Q(address__icontains=query) |
            Q(hard_skills__icontains=query)
        )

    resumes_per_page = 4
    paginator = Paginator(queryset, resumes_per_page)

    page_request_var = 'page'
    page = request.GET.get(page_request_var)

    try:
        queryset = paginator.get_page(page)
    except PageNotAnInteger:
        queryset = paginator.page(paginator.num_pages)
    except EmptyPage:
        queryset = paginator.page(paginator.num_pages)

    context = {
        'resumes': queryset,
        'page_request_var': page_request_var,
        'paginator_range': paginator_array(paginator.num_pages, paginator.get_page(page).number),
        'count_of_pages': paginator.num_pages,
        'count_of_resumes': len(queryset),
        'current_year': get_current_year()
    }

    return render(request, 'employer/home.html', context)


def create_vacancy(request):
    form = EmployerForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        vacancy_ins = form.save(commit=False)
        vacancy_ins.user = request.user
        vacancy_ins.save()

        extra_tags = 'html_safe'

        message = f'<p>The <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/employer/vacancy/{vacancy_ins.id}/">vacancy</a> was successfully created!</p>' \
                  f'<p>To update your vacancy, click <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/employer/update/{vacancy_ins.id}/">here</a></p>'

        messages.info(request, message, extra_tags)

        return redirect('employer:vacancies')

    context = {
        'form': form,
        'text_for_btn': 'Create vacancy',
        'remote_job': '',
        'current_year': get_current_year(),
    }

    return render(request, 'employer/vacancy_creation.html', context)


def update_vacancy(request, id=None):

    vacancy_ins = get_object_or_404(EmployerModel, id=id)
    form = EmployerForm(request.POST or None, request.FILES or None, instance=vacancy_ins)

    if form.is_valid():
        vacancy_ins = form.save(commit=False)
        vacancy_ins.save()

        extra_tags = 'html_safe'

        message = f'<p>The <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/employer/vacancy/{vacancy_ins.id}/">vacancy</a> was successfully updated!</p>' \
                  f'<p>To update again your vacancy, click <a style="text-decoration: none; color: darkblue;" ' \
                  f'href="/employer/update/{vacancy_ins.id}/">here</a></p>'

        messages.info(request, message, extra_tags)

        return redirect('employer:vacancies')

    context = {
        'form': form,
        'text_for_btn': 'Update vacancy',
        'remote_job': vacancy_ins.remote_job,
        'current_year': get_current_year()
    }

    return render(request, 'employer/vacancy_creation.html', context)


def delete_vacancy(request, id=None):
    vacancy_instance = get_object_or_404(EmployerModel, id=id)
    vacancy_instance.delete()

    extra_tags = 'html_safe'
    message = f'<p>Vacancy has just been successfully deleted!</p>'

    messages.info(request, message, extra_tags)

    return redirect('employer:vacancies')


def like_resume(request, id=None):

    resume_obj = get_object_or_404(EmployeeModel, id=id)

    if request.user.is_authenticated:
        user = get_object_or_404(User, id=request.user.id)

        user_id = str(user.id)
        resume_id = resume_obj.id

        with open('additional_files/liked_resumes.json', "r") as file:
            data = json.load(file)

        if user_id in data['users']:
            if resume_id in data['users'][user_id]:
                data['users'][user_id].remove(resume_id)
            else:
                data['users'][user_id].append(resume_id)
        else:
            data['users'][user_id] = [resume_id]

        with open('additional_files/liked_resumes.json', 'w') as file:
            json.dump(data, file)

    return redirect(f'/employer/resume/{resume_obj.id}/')


def resume(request, id=None):

    resume_obj = get_object_or_404(EmployeeModel, id=id)
    size_of_image = set_width_height_for_image(resume_obj.width_field, resume_obj.height_field)

    context = {
        'resume': resume_obj,
        'image_width': size_of_image[0],
        'image_height': size_of_image[1],
        'soft_skills': split_lines(resume_obj.soft_skills),
        'hard_skills': split_lines(resume_obj.hard_skills),
        'user': request.user,
        'current_year': get_current_year()
    }

    if resume_obj.image:
        context['image_existence'] = True
    else:
        context['image_existence'] = False

    if request.user.is_authenticated:
        user = get_object_or_404(User, id=request.user.id)
        context['user_main'] = user

        with open('additional_files/liked_resumes.json', "r") as file:
            data = json.load(file)

        user_id = str(user.id)

        try:
            if resume_obj.id in data['users'][user_id]:
                context['existence_in_liked_resumes'] = True
            else:
                context['existence_in_liked_resumes'] = False
        except KeyError:
            context['existence_in_liked_resumes'] = False

    return render(request, 'employer/resume.html', context)


def own_vacancies(request):
    queryset = [vacancy for vacancy in EmployerModel.objects.all() if vacancy.user == request.user]

    context = {
        'vacancies': queryset,
        'count_of_vacancies': len(queryset),
        'current_year': get_current_year()
    }

    return render(request, 'employer/own_vacancies.html', context)


def vacancy(request, id=None):

    vacancy_obj = get_object_or_404(EmployerModel, id=id)

    context = {
        'vacancy': vacancy_obj,
        'user': request.user,
        'requirements': split_lines(vacancy_obj.requirements_of_job),
        'benefits': split_lines(vacancy_obj.benefits_of_job),
        'responsibilities': split_lines(vacancy_obj.responsibilities_of_job),
        'current_year': get_current_year()
    }

    return render(request, 'employer/vacancy.html', context)


def liked_resumes(request):

    user = get_object_or_404(User, id=request.user.id)

    with open('additional_files/liked_resumes.json', "r") as file:
        data = json.load(file)

    user_id = str(user.id)

    try:
        liked_resumes_user = data['users'][user_id]
        queryset = EmployeeModel.objects.all().filter(id__in=liked_resumes_user)
    except KeyError:
        queryset = EmployeeModel.objects.all().filter(id__in=[0])

    query = request.GET.get('q_liked_r')
    if query:
        queryset = queryset.filter(
            Q(name__icontains=query) |
            Q(main_programming_language__icontains=query) |
            Q(type_of_job__icontains=query) |
            Q(address__icontains=query) |
            Q(hard_skills__icontains=query)
        )

    context = {
        'resumes': queryset,
        'count_of_resumes': len(queryset),
        'add_query': False,
        'current_year': get_current_year()
    }

    if query:
        context['add_query'] = True
    else:
        context['add_query'] = False

    return render(request, 'employer/liked_resumes.html', context)


def respond_to_resume(request, id=None):

    if not request.user.is_authenticated:
        return redirect('users:login')

    resume_obj = get_object_or_404(EmployeeModel, id=id)
    user_obj = get_object_or_404(User, id=request.user.id)

    queryset_of_appropriate_vacancies = EmployerModel.objects.all().filter(user=user_obj)
    number_of_vacancies = len(queryset_of_appropriate_vacancies)

    subject = 'Response to the resume'
    from_email = settings.EMAIL_HOST_USER
    to = resume_obj.email

    # for local site
    prefix_for_url = 'http://127.0.0.1:8000'

    context_for_email = {
        'subject': subject,
        'resume': resume_obj,
        'vacancies': queryset_of_appropriate_vacancies,
        'number_of_vacancies': number_of_vacancies,
        'prefix': prefix_for_url
    }

    if queryset_of_appropriate_vacancies:
        id_for_vacancy = [obj_id.id for obj_id in queryset_of_appropriate_vacancies]
        emails = list(set([obj.email for obj in queryset_of_appropriate_vacancies]))
        phone_numbers = list(set([obj.phone_number for obj in queryset_of_appropriate_vacancies]))

        if number_of_vacancies == 1:
            context_for_email['id_for_vacancy'] = id_for_vacancy[0]
            context_for_email['email'] = emails[0]
            context_for_email['phone_number'] = phone_numbers[0]
        else:
            context_for_email['id_for_vacancy'] = id_for_vacancy
            context_for_email['email'] = emails
            context_for_email['phone_number'] = phone_numbers

    html_content = render_to_string('employer/email_content.html', context_for_email)

    msg = EmailMessage(subject, html_content, from_email, [to])
    msg.content_subtype = "html"
    msg.send()

    extra_tags = 'html_safe'

A_SearchJob/templates/employer/email_content.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ subject }}</title>
</head>
<body>
    <h2 style="text-align: center; margin-top: 10px; color: #162896">
        Hello {{ resume.name }}! I am a bot from SearchJob.
    </h2>

    <p style="font-size: 20px; color: #162896">
        You have received a response to your <a style="text-decoration: none; color: #3f6fd9" href="{{ prefix }}{% url 'employer:resume' resume.id %}">resume</a> - '{{ resume.type_of_job }}.'
    </p>

    <hr style="margin-top: 10px; margin-bottom: 10px;">

    {% if not number_of_vacancies %}
        <p style="font-size: 20px; color: #162896">
            This company does not have any vacancy.
        </p>
    {% elif number_of_vacancies == 1 %}
        <p style="font-size: 20px; color: #162896">
            To see this company's vacancy, click <a style="text-decoration: none; color: #3f6fd9" href="{{ prefix }}{% url 'employee:vacancy' id_for_vacancy %}">here</a>.
        </p>
    {% else %}
        <p style="font-size: 20px; color: #162896">
            To see this company's vacancies click
            {% for obj_id in id_for_vacancy %}
                <a style="text-decoration: none; color: #3f6fd9; margin-left: 20px;" href="{{ prefix }}{% url 'employee:vacancy' obj_id %}">here</a>
            {% endfor %}.
        </p>
    {% endif %}

    <hr style="margin-top: 10px; margin-bottom: 10px;">

    {% if number_of_vacancies %}
        <p style="font-size: 20px; color: #162896">
            All possible ways of contacting this company are collected here (they are not on the vacancy page, as this is personal information) :<br><br>
            {% if number_of_vacancies == 1 %}
                Phone number: {{ phone_number }}<br>
                Email: {{ email }}
            {% elif number_of_vacancies > 1 %}
                {% for number in phone_number %}
                    Phone number: {{ number }}<br>
                {% endfor %}
                <br>
                {% for email_obj in email %}
                    Email: {{ email_obj }}<br>
                {% endfor %}
            {% endif %}
        </p>
        <hr style="margin-top: 10px; margin-bottom: 10px;">
    {% endif %}

    <p style="font-size: 20px; color: #162896">
        Thank you for using our services!
    </p>

</body>
</html>

A_SearchJob/templates/employer/login_in_nav.html
<div style="margin-top: 10px;">
    {% if user.is_authenticated %}
        <div class="text-end" style="margin-right: 10px;">
            <a href="{% url 'employee:home-employee' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-primary me-2">Employee</button></a>
            <a href="{% url 'users:logout' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-danger me-2">Logout</button></a>
        </div>
    {% else %}
        <div class="text-end" style="margin-right: 10px;">
            <a href="{% url 'users:login' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-primary">Login</button></a>
            <a href="{% url 'users:register' %}"><button style="font-size: 20px; border-radius: 10px;" type="button" class="btn btn-outline-success">Register</button></a>
        </div>
    {% endif %}
</div>

A_SearchJob/templates/employer/own_vacancies.html
{% extends 'employer/base_employer_block.html' %}

{% block add_in_nav %}

    <ul class="nav col-12 col-md-6 me-lg-auto mb-2 justify-content-center mb-md-0" style="font-size: 25px;">
        <li><a href="{% url 'employer:home-employer' %}" class="nav-link px-2">Home</a></li>
        <li><a href="{% url 'employer:create' %}" class="nav-link px-2">Create</a></li>
        <li><a href="{% url 'employer:vacancies' %}" class="nav-link px-2 link-secondary">My vacancies</a></li>
        <li><a href="{% url 'employer:liked' %}" class="nav-link px-2">Liked</a></li>
        <li><a href="{% url 'story:home-story' %}" class="nav-link px-2">Stories</a></li>
    </ul>

    {% include 'employer/login_in_nav.html' %}

{% endblock add_in_nav %}

{% block main_content %}

    {% if not count_of_vacancies %}
        <div style="margin-left: 36%; margin-top: 10%;">
            <h1>You have not created any vacancy yet.</h1>
            <h1>To create, click <a href="{% url 'employer:create' %}">here</a></h1>
        </div>
    {% endif %}

    <div class="col-sm-8 col-sm-offset-2" style="margin-top: 50px; margin-bottom: 20px;">
        {% for vacancy in vacancies %}
            <div class="row">
                <div class="col-sm-20" style="margin-bottom: 20px;">
                    <div class="thumbnail" style="border-radius: 10px; border: 3px solid rgba(130,196,15,0.85); box-shadow: 8px 8px 14px rgba(188,211,68,0.92);">
                        <div class="caption" style="padding: 25px;">
                            <div style="display: flex; justify-content: space-between;">
                                <div style="margin-left: 2%; margin-top: 7px;">
                                    <a href="{{ vacancy.get_url_to_vacancy }}" style="text-decoration: none; font-size: 22px; color: #d77500; font-weight: 500;">The whole vacancy</a>
                                </div>
                                <div style="margin-bottom: 10px;">
                                    <p style="text-align: center; font-size: 28px; font-weight: 500; color: #fd9626">{{ vacancy.name_of_job }}</p>
                                </div>
                                <div style="margin-right: 2%; margin-top: 7px;">
                                    <a href="{{ vacancy.get_url_to_update_vacancy }}" style="text-decoration: none; font-size: 22px; color: #d77500; font-weight: 500;">Update</a>
                                </div>
                            </div>

                            <p style="width: 100%; overflow: hidden; margin-top: 20px; font-weight: 400; font-size: 20px; margin-left: 20px;">
                                <span style="padding-right: 30px;">{{ vacancy.name_of_company }}</span>
                                <span style="padding-right: 30px;">{{ vacancy.location }}</span>
                                <span>{{ vacancy.phone_number }}</span>
                                <span style="margin-bottom: 15px; margin-left: 50px; font-weight: 500;">{{ vacancy.main_programming_language }}</span>
                            </p>
                            <hr>
                            <p style="display: flex; justify-content: space-between; font-size: 17px; margin-top: 15px; color: rgba(119,13,72,0.75)">
                                <span>Latest update: {{ vacancy.update|timesince }} тому</span>
                                <a href="{% url 'employer:delete' vacancy.id %}" style="text-decoration: none; font-size: 22px; color: #ff1010; font-weight: 500; ">Delete</a>
                                <span>Published: {{ vacancy.timestamp|timesince }} тому</span>
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock main_content %}

A_SearchJob/templates/employer/resume.html
{% extends 'employer/base_employer_block.html' %}

{% block add_in_nav %}

    <ul class="nav col-12 col-md-6 me-lg-auto mb-2 justify-content-center mb-md-0" style="font-size: 25px;">
        <li><a href="{% url 'employer:home-employer' %}" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="{% url 'employer:create' %}" class="nav-link px-2">Create</a></li>
        <li><a href="{% url 'employer:vacancies' %}" class="nav-link px-2">My vacancies</a></li>
        <li><a href="{% url 'employer:liked' %}" class="nav-link px-2">Liked</a></li>
        <li><a href="{% url 'story:home-story' %}" class="nav-link px-2">Stories</a></li>
    </ul>


    {% include 'employee/login_in_nav.html' %}

{% endblock add_in_nav %}

{% block main_content %}

    <div class="col-sm-8 col-sm-offset-2" style="margin-bottom: 30px; margin-top: 50px;">
        <div class="row">
            <div class="col-sm-20">
                <div class="thumbnail" style="padding: 0; border-radius: 10px; border: 3px solid rgba(178,178,178,0.79); box-shadow: 10px 10px 14px rgba(159,159,159,0.57); display: flex;">
                    <div style="flex: 29%; text-align: center; background-color: aqua; padding: 20px;">
                        {% if image_existence %}
                            <img style="border-radius: 50px; margin-bottom: 20px;" src="{{ resume.image.url }}" width="{{ image_width }}px" height="{{ image_height }}px" alt="Photo of person">
                        {% endif %}

                        <div style="text-align: left;">
                            <h2>Personal information</h2>
                            <hr style="height: 2px; margin-bottom: 20px;">
                            <div>
                                <h4>Name</h4>
                                <p>{{ resume.name }}</p>
                            </div>
                            <div>
                                <h4>Date of birth</h4>
                                <p>{{ resume.birth }}</p>
                            </div>
                            <div style="margin-bottom: 20px;">
                                <h4>Address</h4>
                                <p>{{ resume.address }}</p>
                            </div>

                            <h2>Additional Information</h2>
                            <hr style="height: 2px; margin-bottom: 20px;">
                            <div>
                                <h4>English level</h4>
                                <p>{{ resume.level_of_english }}</p>
                            </div>
                            <div>
                                <h4>Main programming language</h4>
                                <p>{{ resume.main_programming_language }}</p>
                            </div>

                            <h2>Hard skills</h2>
                            <hr style="height: 2px; margin-bottom: 20px;">
                            <ul style="margin-bottom: 20px;">
                                {% for skills in hard_skills %}
                                    <li>{{ skills }}</li>
                                {% endfor %}
                            </ul>

                            <a style="text-decoration: none;" href="{% url 'employer:respond' resume.id %}"><button class="btn btn-outline-primary" style="margin-top: 10px; margin-right: 20px; font-weight: 600; width: 100%; font-size: 25px; padding-bottom: 5px; border-radius: 10px; border: 3px solid rgb(64,108,206); box-shadow: 10px 10px 14px rgba(99,103,192,0.6);">Respond</button></a>

                        </div>

                    </div>

                    <div style="background-color: rgba(178,178,178,0.79); flex: 1px;"></div>

                    <div style="flex: 70%; text-align: left; padding: 10px 20px;">

                        <div style="display: flex; justify-content: space-between;">

                            <h1 style="font-size: 35px; margin-top: 10px;">{{ resume.name }}</h1>

                            {% if user.is_authenticated %}
                                <form action="/employer/like_resume/{{ resume.id }}/">
                                    <button type="submit" style="margin-top: 15px; margin-right: 10px; height: 45px; width: 55px; overflow: hidden; display: inline-block; padding: 0; background: none; border: none; cursor: pointer;">
                                        {% if existence_in_liked_resumes %}
                                            <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 16 16" fill="none">
                                                <path d="M8 2.74805L8 13.7946C11.4523 11.4265 13.3654 9.25313 14.2857 7.43758C15.2413 5.55246 15.1235 4.07583 14.5996 3.05284C13.4859 0.877695 10.4011 0.280067 8.71675 2.01133L8 2.74805ZM8 15C-7.33313 4.86841 3.27876 -3.04087 7.82432 1.14308C7.88395 1.19797 7.94253 1.25493 8 1.314C8.05747 1.25494 8.11605 1.19797 8.17567 1.14309C12.7212 -3.04088 23.3331 4.8684 8 15Z" fill="black"/>
                                            </svg>
                                        {% else %}
                                            <svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 16 16" fill="none">
                                                <path d="M8 2.74805L7.28325 2.01133C5.5989 0.280067 2.51415 0.877695 1.40036 3.05284C0.876534 4.07583 0.75875 5.55246 1.71429 7.43758C2.63457 9.25313 4.54767 11.4265 8 13.7946C11.4523 11.4265 13.3654 9.25313 14.2857 7.43758C15.2413 5.55246 15.1235 4.07583 14.5996 3.05284C13.4859 0.877695 10.4011 0.280067 8.71675 2.01133L8 2.74805ZM8 15C-7.33313 4.86841 3.27876 -3.04087 7.82432 1.14308C7.88395 1.19797 7.94253 1.25493 8 1.314C8.05747 1.25494 8.11605 1.19797 8.17567 1.14309C12.7212 -3.04088 23.3331 4.8684 8 15Z" fill="black"/>
                                            </svg>
                                        {% endif %}
                                    </button>
                                </form>
                            {% endif %}

                        </div>


                        <hr style="height: 2px;">
                        <p style="font-weight: 500; margin-bottom: 30px;">{{ resume.description_about_yourself }}</p>

                        <h2 style="margin-bottom: 10px;">Work experience</h2>
                        <hr style="height: 2px;">
                        <p style="margin-bottom: 20px;">{{ resume.work_experience }}</p>

                        <h2 style="margin-bottom: 10px;">Education and qualification</h2>
                        <hr style="height: 2px;">
                        <p style="margin-bottom: 20px;">{{ resume.education }}</p>

                        <h2 style="margin-bottom: 10px;">Type of work</h2>
                        <hr style="height: 2px;">
                        <p>{{ resume.type_of_job }}</p>
                        <p style="margin-bottom: 20px;">Desired salary: {{ resume.desired_salary }}$ per month</p>

                        <h2 style="margin-bottom: 10px;">Soft skills</h2>
                        <hr style="height: 2px;">
                        <ul style="margin-bottom: 20px;">
                            {% for skill in soft_skills %}
                                <li>{{ skill }}</li>
                            {% endfor %}
                        </ul>

                        <h2 style="margin-bottom: 10px;">Links to the author</h2>
                        <hr style="height: 2px;">
                        <div style="display: flex; justify-content: space-between; margin-bottom: 20px;">
                            {% if resume.link_to_own_website %}
                                <a href="{{ resume.link_to_own_website }}" target="_blank" style="text-decoration: none; color: #5295e5; font-weight: 500; font-size: 15px; margin-left: 25px;">Own site</a>
                            {% endif %}

                            {% if resume.linkedin %}
                                <a href="{{ resume.linkedin }}" target="_blank" style="text-decoration: none; color: #5295e5; font-weight: 500; font-size: 15px;">LinkedIn</a>
                            {% endif %}

                            {% if resume.github %}
                                <a href="{{ resume.github }}" target="_blank" style="text-decoration: none; color: #5295e5; font-weight: 500; font-size: 15px; margin-right: 25px;">GitHub</a>
                            {% endif %}
                        </div>

                        {% if resume.additional_files %}
                            <h2 style="margin-bottom: 10px;">Additional file</h2>
                            <hr style="height: 2px;">
                            <a target="_blank" href="{{ resume.additional_files.url }}" style="text-decoration: none; color: #5295e5; font-weight: 500; font-size: 15px; margin-left: 25px; margin-bottom: 20px;">File</a>
                        {% endif %}

                        <hr style="height: 2px">
                        <p style="display: flex; justify-content: space-between; font-size: 15px; margin-right: 15px; text-align: right; font-weight: 200">
                            {{ resume.timestamp|timesince }} тому
                        </p>

                    </div>

                </div>
            </div>
        </div>
    </div>

{% endblock main_content %}